### ISSUE TITLE
동작하지가 않습니다.

### ISSUE THREAD

**Issue by JiniousChoi** [rurumimic/zookeeper-docker#1]
안녕하세요. 
예로 적어놓으신 주키퍼클러스터용 docker-compose.yml 를 이용해 배포시 정상동작하지 않아 문의드립니다.
2181 포트 자체가 뜨지 않는데요.

```bash
root@zoo1:/apache-zookeeper-3.5.6-bin# netstat -natpl
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:3888            0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:37104           0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.11:37137        0.0.0.0:*               LISTEN      -                   
tcp        0      0 172.28.0.3:41486        172.28.0.2:2888         ESTABLISHED -                   
tcp        0      0 172.28.0.3:47126        10.61.236.162:3128      TIME_WAIT   -                   
tcp        0      0 172.28.0.3:3888         172.28.0.2:39342        ESTABLISHED -                   
tcp        0      0 172.28.0.3:47116        10.61.236.162:3128      TIME_WAIT   -                   
tcp        0      0 172.28.0.3:47124        10.61.236.162:3128      TIME_WAIT   -                   
tcp        0      0 172.28.0.3:47118        10.61.236.162:3128      TIME_WAIT   -                   
tcp        0      0 172.28.0.3:3888         172.28.0.4:55724        ESTABLISHED -                   
root@zoo1:/apache-zookeeper-3.5.6-bin# nc localhost 2181
localhost [127.0.0.1] 2181 (?) : Connection refused
```

근데 재밌는 점은 README.md에서 링크해놓으신 31z4의 docker-compose.yml 은 클러스터로서 정상 동작한다는 점입니다. (거기도 약간의 문제가 있어 수정하였습니다.)

```
version: '3.1'

services:
    zoo1:
        image: 31z4/zookeeper
        restart: always
        hostname: zoo1
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo2:
        image: 31z4/zookeeper
        restart: always
        hostname: zoo2
        ports:
            - 2182:2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888

    zoo3:
        image: 31z4/zookeeper
        restart: always
        hostname: zoo3
        ports:
            - 2183:2181
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
```

정상동작하는 위 docker-compose.yml 에서 (ruru님의 것처럼) image 부분만 31z4에서 library로 수정시 바로 재현이 가능한걸로 봐선 zookeeper 버전과 환경변수의 차이인가 싶은데, 혹시 rurumimic님의 경우 게재해 놓으신 docker-compose.yml 을 (swarm아닌) 싱글 도커 호스트상에서 정상적으로 띄울 수 있으신지 궁금합니다.
